PACKAGE_NAME="linuwu_sense"
PACKAGE_VERSION="25.701"

BUILT_MODULE_NAME[0]="linuwu_sense"
BUILT_MODULE_LOCATION[0]="src"
DEST_MODULE_LOCATION[0]="/kernel/drivers/platform/x86"

MAKE[0]="make KVER=${kernelver} clean && make KVER=${kernelver}"

AUTOINSTALL="yes"
